### ISSUE TITLE
Requesting main frame too early

### ISSUE THREAD

**Issue by max8383283** [TheNetsky/Microsoft-Rewards-Script#18] opened 2023-11-10 18:40 UTC
Hello

I have a problem with my script and i don´t know how to fix it,

![tempsnip](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/150080051/683ac834-eacd-47db-b009-90c6d98c1c54)

**Comment by TheNetsky** [comment] 2023-11-10 21:17
I think there's an issue with punchcards, disable them in the config.

**Comment by mgrimace** [comment] 2023-11-23 18:12
> I think there's an issue with punchcards, disable them in the config.

I'm experiencing the same/similar error and tried disabling the punchcards in the config, still receiving the error:

```bash
[11/23/2023, 1:08:58 PM] [PID:] [LOG] [MAIN] Bot started with 1 clusters
[11/23/2023, 1:08:58 PM] [PID:] [LOG] [MAIN-WORKER] Started tasks for account [redacted]
[11/23/2023, 1:08:59 PM] [PID:] [LOG] [MAIN] Starting DESKTOP browser
[11/23/2023, 1:09:02 PM] [PID:] [LOG] [LOGIN] Already logged in
[11/23/2023, 1:09:02 PM] [PID:] [LOG] [LOGIN-BING] Verifying Bing login
[11/23/2023, 1:09:06 PM] [PID:] [LOG] [LOGIN-BING] Bing login verification passed!
[11/23/2023, 1:09:06 PM] [PID:] [LOG] [LOGIN] Logged in successfully
[11/23/2023, 1:09:13 PM] [PID:] [LOG] [GO-HOME] Visited homepage successfully
[11/23/2023, 1:09:15 PM] [PID:] [LOG] [MAIN-POINTS] Current point count: 39211
[11/23/2023, 1:09:18 PM] [PID:] [LOG] [MAIN-POINTS] You can earn 162 points today
[11/23/2023, 1:09:25 PM] [PID:] [LOG] [GO-HOME] Visited homepage successfully
[11/23/2023, 1:09:25 PM] [PID:] [LOG] [DAILY-SET] All Daily Set" items have already been completed
[11/23/2023, 1:09:25 PM] [PID:] [LOG] [MORE-PROMOTIONS] Started solving "More Promotions" item
[11/23/2023, 1:09:25 PM] [PID:] [ERROR] [ACTIVITY] An error occurred:Error: No element found for selector: [data-bi-id="ENCA_Bing_Adhoc_GlobalHeroBanner_20231106_3"]
[11/23/2023, 1:09:25 PM] [PID:] [LOG] [MORE-PROMOTIONS] All "More Promotion" items have been completed
[11/23/2023, 1:09:25 PM] [PID:] [LOG] [SEARCH-BING] Starting bing searches
[11/23/2023, 1:09:25 PM] [PID:] [LOG] [SEARCH-GOOGLE-TRENDS] Generating search queries, can take a while! | GeoLocale: CA
/root/Microsoft-Rewards-Script/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28
        throw new Error(message);
              ^

Error: Requesting main frame too early!
    at assert (/root/Microsoft-Rewards-Script/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at FrameManager.mainFrame (/root/Microsoft-Rewards-Script/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:223:32)
    at CdpPage.mainFrame (/root/Microsoft-Rewards-Script/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:415:35)
    at CdpPage.goto (/root/Microsoft-Rewards-Script/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:595:31)
    at Search.doSearch (/root/Microsoft-Rewards-Script/dist/functions/activities/Search.js:37:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Activities.doSearch (/root/Microsoft-Rewards-Script/dist/functions/Activities.js:13:13)
    at async MicrosoftRewardsBot.Desktop (/root/Microsoft-Rewards-Script/dist/index.js:141:13)
    at async MicrosoftRewardsBot.runTasks (/root/Microsoft-Rewards-Script/dist/index.js:83:13)
```

**Comment by TheNetsky** [comment] 2023-11-23 20:40
What version is this?

**Comment by mgrimace** [comment] 2023-11-23 20:44
> What version is this?

I'm on v.1.2.5. Did a git pull, updated the system, updated the script config, npm i, rebuild the script, then re-ran the script

**Comment by TheNetsky** [comment] 2023-11-23 20:48
So you're running the version I pushed earlier today?

**Comment by mgrimace** [comment] 2023-11-23 21:59
> So you're running the version I pushed earlier today?

Yes, I went to try it again today and did a hit pull in case it had been fixed. Current version as of around 2:00 pm EST

**Comment by TheNetsky** [comment] 2023-11-23 22:02
You shouldn't use it, wait for the release, I pushed it since im changing some other stuff. So it's untested.

**Comment by PiporGames** [comment] 2023-11-24 00:47
I tried 1.2.5 and Pre 1.3 and can confirm something happens as soon as punchcards/more promotions loads. The script stops, a couple of pages refresh at background (the bing reward homepage ones) and then crashes.

**Comment by TheNetsky** [comment] 2023-11-24 01:03
This is a different type of error, open another bug report.

**Comment by mgrimace** [comment] 2023-11-29 00:25
> You shouldn't use it, wait for the release, I pushed it since im changing some other stuff. So it's untested.

That makes sense. I went back to the v1.2.5 release and disabled punchards, now getting the same error as @PiporGames above. I'll follow-up in the new bug report thread for that one.

**Comment by TheNetsky** [comment] 2023-11-29 08:48
I've identified the issue and hopefully fixed in the upcoming release

**Comment by dubious-senpai** [comment] 2023-11-29 21:42
thank god

**Comment by TheNetsky** [comment] 2023-12-01 11:01
Try 1.3.0, reopen or comment with info if the issue is still present.

**Closed by TheNetsky** 2023-12-01 11:01 UTC
Labels: bug
