### ISSUE TITLE
Search slowing down over time

### ISSUE THREAD

**Issue by serzak51** [TheNetsky/Microsoft-Rewards-Script#100] opened 2024-04-25 12:59 UTC
I have around 15 accounts that i use. The search works fine on the firsts accounts, but after a while the time between searches double after each searching, in the end making it wait ~15 minutes, and probably more if i let it run. Once the script is restarted, it goes on normally. I'm not really sure what is causing this, i checked the search part of the code and everything seems fine.

**Comment by TheNetsky** [comment] 2024-05-25 08:56
Since this has not been confirmed by anyone else, nor myself, I'll close this.

**Closed by TheNetsky** 2024-05-25 08:56 UTC
